import {expect,test,type Page} from "@playwright/test";

const status=(state:"live"|"async")=>({state,label:state==="live"?"Live Chat":"Send us a Message",destinationUrl:null,checkedAt:new Date().toISOString()});
async function mockStatus(page:Page,state:"live"|"async"){await page.route("**/v1/chat/status",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(status(state))}));}
async function mockStart(page:Page,mode:"live"|"async"){await page.route("**/v1/chat/conversations",async route=>{const request=route.request().postDataJSON();await route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({ok:true,conversation:{id:`conversation_${mode}`,resumeToken:`resume_${mode}`,mode},message:{id:`message_${mode}`,client_message_id:request.clientMessageId,sequence:1,sender_kind:"customer",body:request.message,created_at:new Date().toISOString()}})});});}
test.beforeEach(async({page})=>{await page.setViewportSize({width:1440,height:1000});});
async function fillIdentity(page:Page,message:string){await page.getByLabel("Name").fill("Synthetic Visitor");await page.getByLabel("Email").fill("visitor@example.test");await page.getByLabel("How can we help?").fill(message);}

test("desktop header keeps Check Availability primary and opens live chat accessibly",async({page})=>{await page.setViewportSize({width:1440,height:1000});await mockStatus(page,"live");await page.goto("/");const header=page.getByTestId("site-header");const chat=header.getByRole("button",{name:"Live Chat"});const availability=header.getByRole("link",{name:"Check Availability"});await expect(chat).toBeVisible();await expect(availability).toBeVisible();await expect(availability).toHaveCSS("background-color","rgb(244, 122, 0)");await chat.focus();await chat.press("Enter");const dialog=page.getByRole("dialog",{name:"Chat with Focus Lab"});await expect(dialog).toBeVisible();await expect(page.getByRole("button",{name:"Close chat"})).toBeFocused();await page.keyboard.press("Escape");await expect(dialog).toBeHidden();await expect(chat).toBeFocused();});

test("live mode starts and remains a realtime conversation interface",async({page})=>{await mockStatus(page,"live");await mockStart(page,"live");await page.goto("/");await page.getByRole("button",{name:"Live Chat"}).click();await fillIdentity(page,"Synthetic live message");await page.getByRole("button",{name:"Start Conversation"}).click();await expect(page.getByText("Synthetic live message")).toBeVisible();await expect(page.getByLabel("Message")).toBeVisible();await expect(page.getByText("free to close",{exact:false})).toHaveCount(0);});

test("async mode submits once and ends in a clear leave-safe completion state",async({page})=>{await mockStatus(page,"async");await mockStart(page,"async");await page.goto("/");await page.getByRole("button",{name:"Message Us (No Bots)"}).click();await fillIdentity(page,"Synthetic async message");await page.getByRole("button",{name:"Send Message"}).click();await expect(page.getByRole("status")).toContainText("your message has been sent");await expect(page.getByRole("status")).toContainText("free to close this window or leave the website");await expect(page.getByRole("dialog").getByLabel("Message")).toHaveCount(0);await page.getByRole("button",{name:"Done"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);});

test("opened async form keeps async semantics if a later status would be live",async({page})=>{let state:"async"|"live"="async";await page.route("**/v1/chat/status",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(status(state))}));await mockStart(page,"async");await page.goto("/");await page.getByRole("button",{name:"Message Us (No Bots)"}).click();state="live";await fillIdentity(page,"Stable async semantics");await page.getByRole("button",{name:"Send Message"}).click();await expect(page.getByRole("status")).toContainText("free to close");});

test("mobile menu contains secondary chat action and drawer fits a narrow viewport",async({page})=>{await page.setViewportSize({width:390,height:844});await mockStatus(page,"async");await page.goto("/");await expect(page.getByTestId("site-header").getByRole("button",{name:"Message Us (No Bots)"})).toBeHidden();await page.getByRole("button",{name:"Open menu"}).click();const menu=page.getByRole("navigation",{name:"Mobile primary"});await expect(menu.getByRole("button",{name:"Message Us (No Bots)"})).toBeVisible();await expect(menu.getByRole("link",{name:"Check Availability"})).toBeVisible();await menu.getByRole("button",{name:"Message Us (No Bots)"}).click();const drawer=page.getByRole("dialog");await expect(drawer).toBeVisible();const box=await drawer.boundingBox();expect(box?.width).toBeLessThanOrEqual(391);expect(box?.x).toBeGreaterThanOrEqual(0);});

test("safe API failures preserve public form input",async({page})=>{await mockStatus(page,"async");await page.route("**/v1/chat/conversations",route=>route.abort("failed"));await page.goto("/");await page.getByRole("button",{name:"Message Us (No Bots)"}).click();await fillIdentity(page,"Keep this customer message");await page.getByRole("button",{name:"Send Message"}).click();await expect(page.getByRole("dialog").getByRole("alert")).toContainText("couldn't send");await expect(page.getByLabel("How can we help?")).toHaveValue("Keep this customer message");});
