import { env,exports } from "cloudflare:workers";
import { beforeEach,describe,expect,it } from "vitest";
const token="development-test-token-00000000";const responder="rsp_chat_staff";const auth={Authorization:`Bearer ${token}`,"X-Development-Responder-Id":responder,"Content-Type":"application/json"};
beforeEach(async()=>{const now=new Date().toISOString();await env.DB.prepare("INSERT INTO responders (id,display_label,active,created_at,updated_at) VALUES (?,?,?,?,?)").bind(responder,"Synthetic Chat Responder",1,now,now).run();});
async function start(overrides:Record<string,unknown>={}){return exports.default.fetch(new Request("https://operations.example.test/v1/chat/conversations",{method:"POST",headers:{"Content-Type":"application/json","CF-Connecting-IP":"192.0.2.44"},body:JSON.stringify({name:"Synthetic Visitor",email:`visitor-${crypto.randomUUID()}@example.test`,message:"Is anyone available to discuss a synthetic event?",clientMessageId:crypto.randomUUID(),website:"",...overrides})}));}
describe("native website chat",()=>{
  it("persists a conversation and ordered initial message",async()=>{const response=await start();expect(response.status).toBe(201);const body=await response.json<{conversation:{id:string;resumeToken:string;mode:string};message:{sequence:number}}>();expect(body.conversation.resumeToken).toHaveLength(64);expect(body.message.sequence).toBe(1);expect(await env.DB.prepare("SELECT COUNT(*) AS count FROM conversation_messages WHERE conversation_id=?").bind(body.conversation.id).first<number>("count")).toBe(1);});
  it("resumes securely and deduplicates a retried customer message",async()=>{const created=await (await start()).json<{conversation:{id:string;resumeToken:string}}>();const path=`/v1/chat/conversations/${created.conversation.id}/messages`;const clientMessageId=crypto.randomUUID();const request=()=>new Request(`https://operations.example.test${path}`,{method:"POST",headers:{"Content-Type":"application/json","X-Chat-Resume-Token":created.conversation.resumeToken,"CF-Connecting-IP":"192.0.2.45"},body:JSON.stringify({body:"Synthetic follow-up",clientMessageId})});expect((await exports.default.fetch(request())).status).toBe(201);expect((await exports.default.fetch(request())).status).toBe(201);expect(await env.DB.prepare("SELECT COUNT(*) AS count FROM conversation_messages WHERE conversation_id=? AND client_message_id=?").bind(created.conversation.id,clientMessageId).first<number>("count")).toBe(1);expect((await exports.default.fetch(new Request(`https://operations.example.test${path}?resume=wrong`))).status).toBe(403);});
  it("lets authenticated staff read, reply, assign, and mark read",async()=>{const created=await (await start()).json<{conversation:{id:string}}>();const base=`https://operations.example.test/v1/internal/conversations/${created.conversation.id}`;expect((await exports.default.fetch(new Request(base))).status).toBe(401);let response=await exports.default.fetch(new Request(base,{headers:auth}));expect(response.status).toBe(200);response=await exports.default.fetch(new Request(`${base}/assignment`,{method:"PATCH",headers:auth,body:JSON.stringify({responderId:responder})}));expect(response.status).toBe(200);response=await exports.default.fetch(new Request(`${base}/messages`,{method:"POST",headers:auth,body:JSON.stringify({body:"Synthetic staff response",clientMessageId:crypto.randomUUID()})}));expect(response.status).toBe(201);expect(await env.DB.prepare("SELECT sender_responder_id FROM conversation_messages WHERE sender_kind='responder'").first<string>("sender_responder_id")).toBe(responder);});
  it("uses confirmed presence for live versus async",async()=>{let status=await (await exports.default.fetch(new Request("https://operations.example.test/v1/chat/status"))).json<{state:string}>();expect(status.state).toBe("async");await exports.default.fetch(new Request("https://operations.example.test/v1/internal/presence/heartbeat",{method:"POST",headers:auth,body:JSON.stringify({available:true})}));status=await (await exports.default.fetch(new Request("https://operations.example.test/v1/chat/status"))).json();expect(status.state).toBe("live");});
  it("rejects malformed and honeypot submissions safely",async()=>{expect((await start({message:""})).status).toBe(422);expect((await start({website:"spam.example"})).status).toBe(400);});
});
