import { env,exports } from "cloudflare:workers";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { dispatchPushEvent,sendTestNotification,type PushSender } from "../src/push";

const token="development-test-token-00000000";const responderA="rsp_push_a";const responderB="rsp_push_b";
const auth=(responderId=responderA)=>({Authorization:`Bearer ${token}`,"X-Development-Responder-Id":responderId,"Content-Type":"application/json"});
const subscription=(suffix:string)=>({endpoint:`https://push.example.test/subscription/${suffix}`,expirationTime:null,keys:{p256dh:"p".repeat(65),auth:"a".repeat(24)}});
async function api(path:string,init:RequestInit={},responderId=responderA){return exports.default.fetch(new Request(`https://operations.example.test${path}`,{...init,headers:{...auth(responderId),...init.headers}}));}
async function register(suffix:string,responderId=responderA){return api("/v1/internal/push/subscriptions",{method:"PUT",body:JSON.stringify(subscription(suffix))},responderId);}
async function seedConversation(assignedResponderId:string|null=null){const now=new Date().toISOString();const contact=`con_${crypto.randomUUID()}`;const conversation=`cv_${crypto.randomUUID()}`;await env.DB.batch([
  env.DB.prepare("INSERT INTO contacts VALUES (?,?,?,?,?,?,?)").bind(contact,"Push Test Customer",`${contact}@example.test`,null,"email",now,now),
  env.DB.prepare(`INSERT INTO conversations (id,contact_id,provider,channel_state,assigned_responder_id,created_at,updated_at) VALUES (?,?,'native_web','open',?,?,?)`).bind(conversation,contact,assignedResponderId,now,now),
  env.DB.prepare("INSERT INTO conversation_messages VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),conversation,crypto.randomUUID(),1,"customer",null,"Private synthetic message",now),
]);return conversation;}
function event(conversationId:string,overrides:Record<string,unknown>={}){return{id:`message:${crypto.randomUUID()}`,type:"conversation:new",conversationId,sequence:1,senderKind:"customer",assignedResponderId:null,createdAt:new Date().toISOString(),...overrides};}

beforeEach(async()=>{const now=new Date().toISOString();await env.DB.batch([
  env.DB.prepare("INSERT INTO responders (id,display_label,active,role,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(responderA,"Push Responder A",1,"responder",now,now),
  env.DB.prepare("INSERT INTO responders (id,display_label,active,role,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(responderB,"Push Manager B",1,"manager",now,now),
]);});

describe("authenticated push subscriptions",()=>{
  it("rejects unauthenticated registration",async()=>{const response=await exports.default.fetch(new Request("https://operations.example.test/v1/internal/push/subscriptions",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(subscription("unauthorized"))}));expect(response.status).toBe(401);});
  it("registers multiple devices per responder and removes only the requested device",async()=>{expect((await register("phone")).status).toBe(201);expect((await register("desktop")).status).toBe(201);expect(await env.DB.prepare("SELECT COUNT(*) AS count FROM push_subscriptions WHERE responder_id=?").bind(responderA).first<number>("count")).toBe(2);expect((await api("/v1/internal/push/subscriptions",{method:"DELETE",body:JSON.stringify({endpoint:subscription("phone").endpoint})})).status).toBe(200);expect(await env.DB.prepare("SELECT endpoint FROM push_subscriptions WHERE responder_id=?").bind(responderA).first<string>("endpoint")).toBe(subscription("desktop").endpoint);});
  it("reports whether the authenticated device exists in D1",async()=>{await register("status");const response=await api("/v1/internal/push/status",{method:"POST",body:JSON.stringify({endpoint:subscription("status").endpoint})});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({ok:true,registered:true,enabled:true});});
  it("preserves existing schema data through the push migration",async()=>{expect(await env.DB.prepare("SELECT id FROM responders WHERE id=?").bind(responderA).first<string>("id")).toBe(responderA);expect(await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='push_subscriptions'").first<string>("name")).toBe("push_subscriptions");});
});

describe("push routing and delivery",()=>{
  it("routes a new unassigned live chat only to confirmed-available responders with a non-PII payload",async()=>{await register("a",responderA);await register("b",responderB);const now=new Date();await env.DB.prepare("INSERT INTO responder_presence VALUES (?,?,?,?,?)").bind(responderA,1,now.toISOString(),new Date(now.getTime()+120_000).toISOString(),now.toISOString()).run();const conversation=await seedConversation();const sent:unknown[][]=[];const sender:PushSender=vi.fn(async(...args)=>{sent.push(args);return{statusCode:201};});await dispatchPushEvent(env,event(conversation),sender);expect(sent).toHaveLength(1);expect((sent[0]![0] as {endpoint:string}).endpoint).toBe(subscription("a").endpoint);const payload=JSON.parse(String(sent[0]![1])) as Record<string,unknown>;expect(payload).toMatchObject({type:"live_chat",title:"New Focus Lab live chat",body:"A customer is waiting for a reply.",conversationId:conversation,badge:1});expect(JSON.stringify(payload)).not.toContain("Push Test Customer");expect(JSON.stringify(payload)).not.toContain("Private synthetic message");});
  it("routes an assigned message only to the assigned responder",async()=>{await register("a",responderA);await register("b",responderB);const conversation=await seedConversation(responderB);const endpoints:string[]=[];const sender:PushSender=async(sub)=>{endpoints.push(sub.endpoint);return{statusCode:201};};await dispatchPushEvent(env,event(conversation,{sequence:2,type:"message:new",assignedResponderId:responderB}),sender);expect(endpoints).toEqual([subscription("b").endpoint]);});
  it("uses manager/admin fallback wording for async unassigned messages",async()=>{await register("a",responderA);await register("b",responderB);const conversation=await seedConversation();const payloads:string[]=[];await dispatchPushEvent(env,event(conversation),async(_sub,payload)=>{payloads.push(payload);return{statusCode:201};});expect(payloads).toHaveLength(1);expect(JSON.parse(payloads[0]!)).toMatchObject({type:"async_message",title:"New Focus Lab message"});});
  it("suppresses responder messages, duplicate events, and foreground subscriptions",async()=>{await register("a",responderA);const conversation=await seedConversation(responderA);const sender=vi.fn(async()=>({statusCode:201}));const same=event(conversation,{sequence:2,assignedResponderId:responderA});await dispatchPushEvent(env,{...same,senderKind:"responder"},sender);await dispatchPushEvent(env,same,sender);await dispatchPushEvent(env,same,sender);expect(sender).toHaveBeenCalledTimes(1);await env.DB.prepare("UPDATE push_subscriptions SET active_until=? WHERE responder_id=?").bind(new Date(Date.now()+60_000).toISOString(),responderA).run();await dispatchPushEvent(env,event(conversation,{sequence:3,assignedResponderId:responderA}),sender);expect(sender).toHaveBeenCalledTimes(1);});
  it("disables dead subscriptions without affecting persisted messages",async()=>{await register("dead",responderA);const conversation=await seedConversation(responderA);const failure=Object.assign(new Error("Gone"),{statusCode:410});await dispatchPushEvent(env,event(conversation,{sequence:2,assignedResponderId:responderA}),async()=>{throw failure;});expect(await env.DB.prepare("SELECT enabled FROM push_subscriptions WHERE responder_id=?").bind(responderA).first<number>("enabled")).toBe(0);expect(await env.DB.prepare("SELECT COUNT(*) AS count FROM conversation_messages WHERE conversation_id=?").bind(conversation).first<number>("count")).toBe(1);expect(await env.DB.prepare("SELECT status FROM push_deliveries WHERE conversation_id=?").bind(conversation).first<string>("status")).toBe("failed");});
  it("sends a conservative server-generated test notification to the requested owned device",async()=>{await register("test",responderA);const payloads:string[]=[];const result=await sendTestNotification(env,responderA,subscription("test").endpoint,async(_subscription,payload)=>{payloads.push(payload);return{statusCode:201};});expect(result).toMatchObject({status:200,body:{ok:true,status:"delivered",acceptedStatus:201}});expect(JSON.parse(payloads[0]!)).toMatchObject({type:"test",title:"Focus Lab test notification",body:"Server push notifications are working.",url:"/#/settings"});});
});
