import type { Metadata } from "next";
import { PageHero } from "@/components/sections/PageHero";
import { Button } from "@/components/ui/Button";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Eyebrow, Lead, SectionHeading } from "@/components/ui/Typography";
import { config } from "@/lib/config";

export const metadata: Metadata = { title: "Our Approach", description: "How Focus Lab coordinates event media, entertainment, and production around one shared plan." };

export default function AboutPage() {
  return (
    <>
      <PageHero variant="textLed" eyebrow="Our Approach" title="One shared plan. Specialists who understand the room." body="Focus Lab coordinates event media, entertainment, and production around the same event sequence—without inventing a public team story." />
      <Section><Container><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><Eyebrow>One event plan</Eyebrow><SectionHeading className="mt-4">Attention before equipment.</SectionHeading><Lead className="mt-5">Start with the event, the people, and the moments that need protection. Then choose the capabilities that belong in the plan.</Lead></div><ol className="grid overflow-hidden rounded-media border border-border md:grid-cols-3">{[{n:"01",t:"Moments",b:"Map what needs to happen and when."},{n:"02",t:"Capabilities",b:"Assign only the services that serve the event."},{n:"03",t:"Ownership",b:"Clarify cues, scope, and operating boundaries."}].map((item) => <li key={item.n} className="border-b border-border bg-surface p-6 last:border-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="text-sm font-black text-brand-primary">{item.n}</span><h3 className="mt-12 text-xl font-extrabold">{item.t}</h3><p className="mt-3 text-sm leading-6 text-ink-muted">{item.b}</p></li>)}</ol></div></Container></Section>
      <Section theme="dark"><Container><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><Eyebrow>Cultural fluency</Eyebrow><SectionHeading className="mt-4">Support the room without turning culture into a template.</SectionHeading><p className="mt-5 text-lg leading-8 text-on-brand/68">Language capability can help planning and hosting feel more natural. Exact needs should still be discussed event by event.</p></div><div className="grid grid-cols-2 gap-3">{config.languages.map((language) => <div key={language} className="rounded-card border border-on-brand/15 bg-on-brand/[.04] p-5 text-center text-lg font-extrabold">{language}</div>)}</div></div></Container></Section>
      <Section><Container><div className="grid gap-10 lg:grid-cols-[.78fr_1.22fr]"><div><Eyebrow>Experience, honestly framed</Eyebrow><SectionHeading className="mt-4">Confidence without unsupported numbers.</SectionHeading></div><div><Lead>Focus Lab&apos;s public site does not invent event counts, awards, years of experience, or biographies. Confidence comes from a clear process, exact scope, and how the selected team works with the room.</Lead><div className="mt-8 grid gap-4 sm:grid-cols-2">{[{t:"Planners",b:"Share the run of show, ownership, and cue dependencies."},{t:"Venues",b:"Resolve access, timing, power, effects, and operating rules."},{t:"Other vendors",b:"Clarify interfaces without claiming to replace every specialist."},{t:"Families + hosts",b:"Keep communication focused on the event people are actually planning."}].map((item) => <article key={item.t} className="rounded-card border border-border bg-surface p-6"><h3 className="text-xl font-extrabold">{item.t}</h3><p className="mt-3 text-sm leading-6 text-ink-muted">{item.b}</p></article>)}</div></div></div></Container></Section>
      <Section theme="alt"><Container><div className="grid gap-8 lg:grid-cols-2"><div><Eyebrow>Service area</Eyebrow><SectionHeading className="mt-4">Based around {config.serviceArea}.</SectionHeading><Lead className="mt-5">Share the venue or city in the inquiry. Travel policy and any related costs remain intentionally unresolved until verified.</Lead></div><div className="rounded-media border border-dashed border-border bg-surface p-8"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-brand-primary">Planning note</p><p className="mt-4 text-lg font-extrabold">A destination or travel-heavy event moves into custom scope.</p><p className="mt-3 leading-7 text-ink-muted">No radius, response time, or travel-fee promise is fabricated in this prototype.</p></div></div></Container></Section>
      <Section theme="brand"><Container><div className="grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div><Eyebrow className="!text-ink/70">Start the shared plan</Eyebrow><SectionHeading className="mt-4">Tell us the event before the equipment.</SectionHeading></div><Button href="/check-availability" variant="secondary" className="border-ink bg-ink text-on-brand hover:bg-ink/85">Check Availability <span className="ml-2" aria-hidden="true">→</span></Button></div></Container></Section>
    </>
  );
}
