import { describe,expect,it,vi } from "vitest";
import { createAlertDeduplicator,createChatAudioController,notifyChatEvent,setSoundsEnabled,soundsEnabled,type ChatAlertEvent } from "./chatNotifications";

const conversationEvent:ChatAlertEvent={id:"evt-conversation",type:"conversation:new",conversationId:"conversation-1"};
const messageEvent:ChatAlertEvent={id:"evt-message",type:"message:new",conversationId:"conversation-1"};

describe("chat notifications",()=>{
  it("invokes the strong chime for a new-conversation realtime event",async()=>{const play=vi.fn().mockResolvedValue(true);expect(await notifyChatEvent(conversationEvent,{sounds:true,acceptEvent:()=>true},{play})).toBe(true);expect(play).toHaveBeenCalledWith("conversation:new");});
  it("invokes the subtle chime for a subsequent inbound event",async()=>{const play=vi.fn().mockResolvedValue(true);expect(await notifyChatEvent(messageEvent,{sounds:true,acceptEvent:()=>true},{play})).toBe(true);expect(play).toHaveBeenCalledWith("message:new");});
  it("does not chime when sounds are off",async()=>{const play=vi.fn();expect(await notifyChatEvent(messageEvent,{sounds:false,acceptEvent:()=>true},{play})).toBe(false);expect(play).not.toHaveBeenCalled();});
  it("does not double-chime a duplicate event",async()=>{const play=vi.fn().mockResolvedValue(true);const acceptEvent=createAlertDeduplicator();await notifyChatEvent(messageEvent,{sounds:true,acceptEvent},{play});await notifyChatEvent(messageEvent,{sounds:true,acceptEvent},{play});expect(play).toHaveBeenCalledOnce();});
  it("intentionally suppresses audio for the active conversation",async()=>{const play=vi.fn();expect(await notifyChatEvent(messageEvent,{sounds:true,activeConversationId:"conversation-1",acceptEvent:()=>true},{play})).toBe(false);expect(play).not.toHaveBeenCalled();});
  it("does not let failed audio playback break chat event handling",async()=>{const play=vi.fn().mockRejectedValue(new Error("blocked"));await expect(notifyChatEvent(messageEvent,{sounds:true,acceptEvent:()=>true},{play})).resolves.toBe(false);});
  it("resumes suspended audio from a normal user interaction",async()=>{const audio=mockAudioContext("suspended");const controller=createChatAudioController(()=>audio.context);expect(controller.state()).toBe("uninitialized");await expect(controller.unlock()).resolves.toBe("running");expect(audio.resume).toHaveBeenCalledOnce();});
  it("synthesizes three audible notes for strong and one for subtle",async()=>{const audio=mockAudioContext("running");const controller=createChatAudioController(()=>audio.context);expect(await controller.play("conversation:new")).toBe(true);expect(audio.starts).toHaveLength(3);expect(audio.peaks).toEqual([.16,.16,.16]);audio.starts.length=0;audio.peaks.length=0;expect(await controller.play("message:new")).toBe(true);expect(audio.starts).toHaveLength(1);expect(audio.peaks).toEqual([.16]);});
  it("persists the sound preference",()=>{const values=new Map<string,string>();const storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>void values.set(key,value)};expect(soundsEnabled(storage)).toBe(true);setSoundsEnabled(false,storage);expect(soundsEnabled(storage)).toBe(false);setSoundsEnabled(true,storage);expect(soundsEnabled(storage)).toBe(true);});
});

function mockAudioContext(initial:AudioContextState){let state=initial;const starts:number[]=[];const peaks:number[]=[];const resume=vi.fn(async()=>{state="running";});const destination={} as AudioDestinationNode;const context={get state(){return state;},currentTime:10,destination,resume,createOscillator(){return{frequency:{value:0},type:"sine",connect(node:AudioNode){return node;},start(at:number){starts.push(at);},stop:vi.fn()} as unknown as OscillatorNode;},createGain(){const gainNode={gain:{setValueAtTime:vi.fn(),exponentialRampToValueAtTime(value:number){if(value>.001)peaks.push(value);}},connect(node:AudioNode){return node;}};return gainNode as unknown as GainNode;}} as unknown as AudioContext;return{context,resume,starts,peaks};}
