import { DurableObject } from "cloudflare:workers";
import { dispatchPushEvent } from "./push";

type ChatPayload={senderKind:"customer"|"responder";senderResponderId:string|null;body:string;clientMessageId:string};
type SocketAttachment={kind:"customer"|"responder";conversationId:string;responderId?:string};

export class ChatRoom extends DurableObject<Env>{
  async fetch(request:Request){const url=new URL(request.url);
    if(url.pathname==="/connect")return this.acceptConnection(request,url);
    if(url.pathname==="/message"&&request.method==="POST")return this.persist(url.searchParams.get("conversationId"),await request.json<ChatPayload>());
    return new Response("Not found",{status:404});
  }
  private acceptConnection(request:Request,url:URL){if(request.headers.get("Upgrade")!=="websocket")return new Response("WebSocket required",{status:426});const pair=new WebSocketPair();const client=pair[0];const server=pair[1];const kind=url.searchParams.get("kind")==="responder"?"responder":"customer";const conversationId=url.searchParams.get("conversationId");if(!conversationId)return new Response("Conversation required",{status:400});const attachment:SocketAttachment={kind,conversationId,...(url.searchParams.get("responderId")?{responderId:url.searchParams.get("responderId")!}:{})};this.ctx.acceptWebSocket(server);server.serializeAttachment(attachment);return new Response(null,{status:101,webSocket:client});}
  private async persist(conversationId:string|null,payload:ChatPayload){if(!conversationId)return new Response("Invalid room",{status:400});const existing=await this.env.DB.prepare("SELECT id,sequence,sender_kind,body,created_at FROM conversation_messages WHERE conversation_id=? AND client_message_id=?").bind(conversationId,payload.clientMessageId).first();if(existing)return Response.json({message:existing,idempotentReplay:true});const current=await this.env.DB.prepare("SELECT COALESCE(MAX(sequence),0) AS sequence FROM conversation_messages WHERE conversation_id=?").bind(conversationId).first<{sequence:number}>();const sequence=Number(current?.sequence??0)+1;const now=new Date().toISOString();const id=crypto.randomUUID();await this.env.DB.batch([
      this.env.DB.prepare("INSERT INTO conversation_messages VALUES (?,?,?,?,?,?,?,?)").bind(id,conversationId,payload.clientMessageId,sequence,payload.senderKind,payload.senderResponderId,payload.body,now),
      this.env.DB.prepare(`UPDATE conversations SET updated_at=?,last_message_at=?,last_customer_message_at=CASE WHEN ?='customer' THEN ? ELSE last_customer_message_at END WHERE id=?`).bind(now,now,payload.senderKind,now,conversationId),
      this.env.DB.prepare("INSERT INTO conversation_activity VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),conversationId,payload.senderKind,payload.senderResponderId,payload.senderKind==="customer"?"customer_message_received":"responder_message_sent","{}",now),
    ]);const conversation=await this.env.DB.prepare("SELECT assigned_responder_id FROM conversations WHERE id=?").bind(conversationId).first<{assigned_responder_id:string|null}>();const message={id,client_message_id:payload.clientMessageId,sequence,sender_kind:payload.senderKind,sender_responder_id:payload.senderResponderId,body:payload.body,created_at:now};this.broadcast({type:"message",conversationId,message});const hub=this.env.CHAT_STAFF_HUB;if(hub)await hub.getByName("staff-events").fetch("https://staff-hub/event",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:`message:${id}`,type:sequence===1?"conversation:new":"message:new",conversationId,sequence,senderKind:payload.senderKind,assignedResponderId:conversation?.assigned_responder_id??null,createdAt:now})});return Response.json({message},{status:201});}
  private broadcast(value:unknown){const text=JSON.stringify(value);for(const socket of this.ctx.getWebSockets()){try{socket.send(text);}catch{socket.close(1011,"Delivery failed");}}}
  async webSocketMessage(socket:WebSocket,message:string|ArrayBuffer){if(typeof message!=="string")return;try{const attachment=socket.deserializeAttachment() as SocketAttachment;const payload=JSON.parse(message) as ChatPayload;const result=await this.persist(attachment.conversationId,payload);socket.send(JSON.stringify({type:"ack",...(await result.json<object>())}));}catch{socket.send(JSON.stringify({type:"error",message:"Message was not saved"}));}}
  async webSocketClose(socket:WebSocket,code:number,reason:string){socket.close(code,reason);}
}

export class StaffChatHub extends DurableObject<Env>{
  async fetch(request:Request){const url=new URL(request.url);if(url.pathname==="/connect")return this.acceptConnection(request,url);if(url.pathname==="/event"&&request.method==="POST"){const event=await request.json<Record<string,unknown>>();await this.deliver(event);return new Response(null,{status:204});}return new Response("Not found",{status:404});}
  private acceptConnection(request:Request,url:URL){if(request.headers.get("Upgrade")!=="websocket")return new Response("WebSocket required",{status:426});const responderId=url.searchParams.get("responderId");if(!responderId)return new Response("Responder required",{status:400});const pair=new WebSocketPair();const client=pair[0];const server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({responderId});return new Response(null,{status:101,webSocket:client});}
  private async deliver(event:Record<string,unknown>){if(event.senderKind!=="customer")return;const now=new Date().toISOString();const available=await this.env.DB.prepare(`SELECT r.id FROM responders r JOIN responder_presence p ON p.responder_id=r.id WHERE r.active=1 AND p.available=1 AND p.expires_at>?`).bind(now).all<{id:string}>();const targets=new Set(event.assignedResponderId?[String(event.assignedResponderId)]:available.results.map((row)=>row.id));const payload=JSON.stringify(event);for(const socket of this.ctx.getWebSockets()){const attachment=socket.deserializeAttachment() as {responderId?:string}|null;if(attachment?.responderId&&targets.has(attachment.responderId)){try{socket.send(payload);}catch{socket.close(1011,"Delivery failed");}}}this.ctx.waitUntil(dispatchPushEvent(this.env,event as Parameters<typeof dispatchPushEvent>[1]).catch((error)=>console.error(JSON.stringify({message:"staff push dispatch failed",error:error instanceof Error?error.message:"Unknown error"}))));}
  async webSocketMessage(socket:WebSocket,message:string|ArrayBuffer){if(message==="ping")socket.send("pong");}
  async webSocketClose(socket:WebSocket,code:number,reason:string){socket.close(code,reason);}
}
