export type MediaTruth = "ai-brand" | "authentic-approved" | "authentic-pending" | "development-placeholder";
export type MediaAsset = { id: string; src: string; alt: string; purpose: string; truth: MediaTruth; desktopAspect: string; mobileAspect: string; objectPosition?: string; priority?: "P0" | "P1" | "P2" };
const placeholder = (id: string, src: string, alt: string, purpose: string, desktopAspect = "16/9", mobileAspect = "4/5", objectPosition = "center"): MediaAsset => ({ id, src, alt, purpose, truth: "development-placeholder", desktopAspect, mobileAspect, objectPosition });
export const media = {
  homeHero: placeholder("HOME-HERO-01", "/images/hero-south-asian-reception-wide.jpg", "Guests celebrating together at a warmly lit reception", "Home hero", "16/10", "4/5", "72% center"),
  eventSouthAsian: placeholder("HOME-EVENT-SA-01", "/images/event-card-south-asian.jpg", "Family celebrating at a South Asian wedding", "South Asian event path", "4/5", "4/5"),
  eventWedding: placeholder("HOME-EVENT-WEDDING-01", "/images/event-card-wedding.jpg", "Couple together at an evening wedding", "Wedding event path", "4/5", "4/5"),
  eventParty: placeholder("HOME-EVENT-PARTY-01", "/images/event-card-party.jpg", "Guests dancing at a private celebration", "Party event path", "4/5", "4/5"),
  eventCorporate: placeholder("HOME-EVENT-CORP-01", "/images/event-card-corporate.jpg", "Guests gathering at a professional event", "Corporate event path", "4/5", "4/5"),
  capture: placeholder("HOME-CAPTURE-01", "/images/featured-family-emotion.jpg", "A candid family moment before an event", "Photo and video capability", "3/2", "4/3"),
  production: placeholder("HOME-PRODUCTION-01", "/images/featured-room-lighting.jpg", "An event room prepared with stage lighting", "Entertainment and production capability", "3/2", "4/3"),
  weddingsHero: placeholder("WEDDINGS-HERO-01", "/images/wedding-couple-night.jpg", "A couple outside an evening wedding venue", "Weddings hero", "16/9", "4/5", "center right"),
  weddingCoordination: placeholder("WEDDINGS-COORDINATION-01", "/images/featured-dancefloor-wide.jpg", "Guests gathered for a coordinated reception moment", "Wedding coordination", "3/2", "4/3"),
  southAsianHero: placeholder("SA-HERO-01", "/images/sa-ceremony-wide.jpg", "A contemporary South Asian wedding ceremony", "South Asian weddings hero", "16/9", "4/5", "center right"),
  southAsianBaraat: placeholder("SA-BARAAT-01", "/images/sa-entrance-reaction.jpg", "Family reacting during a wedding entrance", "South Asian event sequence", "3/2", "4/5"),
  southAsianMehndi: placeholder("SA-MEHNDI-01", "/images/sa-mehndi-color.jpg", "A colorful pre-wedding family celebration", "South Asian event sequence", "3/2", "4/5"),
  southAsianReception: placeholder("SA-RECEPTION-01", "/images/hero-south-asian-reception-wide.jpg", "Guests celebrating at a South Asian reception", "South Asian production", "16/10", "4/5"),
  partyHero: placeholder("PARTY-HERO-01", "/images/party-birthday-wide.jpg", "Friends celebrating together at a private party", "Parties hero", "16/9", "4/5", "center right"),
  corporateHero: placeholder("CORP-HERO-01", "/images/corporate-stage-wide.jpg", "A professional event with a stage and seated audience", "Corporate hero", "16/9", "4/5", "center right"),
  photoVideoHero: placeholder("PHOTO-VIDEO-HERO-01", "/images/featured-filmmaker-bts.jpg", "Camera equipment framing an event stage", "Photo video hero", "16/9", "4/5", "center right"),
  photoVideoDetail: placeholder("PHOTO-VIDEO-DETAIL-01", "/images/detail-hands-texture.jpg", "A close candid detail of hands, fabric and jewelry", "Photo video detail", "3/2", "4/3"),
  productionHero: placeholder("PRODUCTION-HERO-01", "/images/featured-dj-action.jpg", "Guests dancing beneath colorful event lighting", "Production hero", "16/9", "4/5", "center right"),
  heroReception: placeholder("legacy-hero", "/images/hero-south-asian-reception-wide.jpg", "Reception", "Legacy"),
  featuredFamilyEmotion: placeholder("legacy-family", "/images/featured-family-emotion.jpg", "Family moment", "Legacy"),
  featuredDancefloorWide: placeholder("legacy-dance", "/images/featured-dancefloor-wide.jpg", "Dance floor", "Legacy"),
  featuredRoomLighting: placeholder("legacy-lighting", "/images/featured-room-lighting.jpg", "Room lighting", "Legacy"),
  featuredFilmmakerBts: placeholder("legacy-film", "/images/featured-filmmaker-bts.jpg", "Film equipment", "Legacy"),
  socialContentVertical: placeholder("legacy-social", "/images/social-content-vertical.jpg", "Vertical filming", "Legacy"),
  processCoordination: placeholder("legacy-process", "/images/process-coordination.jpg", "Event planning", "Legacy"),
  saMehndiColor: placeholder("legacy-mehndi", "/images/sa-mehndi-color.jpg", "Mehndi", "Legacy"),
  saCeremonyWide: placeholder("legacy-sa-ceremony", "/images/sa-ceremony-wide.jpg", "Ceremony", "Legacy"),
  saEntranceReaction: placeholder("legacy-sa-entrance", "/images/sa-entrance-reaction.jpg", "Entrance", "Legacy"),
  saGenerations: placeholder("legacy-sa-family", "/images/sa-generations.jpg", "Family", "Legacy"),
  partyBirthdayWide: placeholder("legacy-party", "/images/party-birthday-wide.jpg", "Party", "Legacy"),
  partyMcCrowd: placeholder("legacy-mc", "/images/party-mc-crowd.jpg", "MC", "Legacy"),
  weddingCoupleNight: placeholder("legacy-wedding", "/images/wedding-couple-night.jpg", "Couple", "Legacy"),
  detailHandsTexture: placeholder("legacy-detail", "/images/detail-hands-texture.jpg", "Detail", "Legacy"),
  corporateStageWide: placeholder("legacy-corporate", "/images/corporate-stage-wide.jpg", "Stage", "Legacy"),
  productionEffects: placeholder("PRODUCTION-EFFECTS-01", "/images/featured-room-lighting.jpg", "A ballroom arranged with event lighting", "Production effects", "3/2", "4/5"),
} as const;

export const teamPortraitPlaceholder: MediaAsset = placeholder("team-needed", "/brand/focus-lab-mark.svg", "", "Team asset", "4/5", "4/5");
