"use client";
import { useEffect,useRef,useState } from "react";

type Message={id:string;client_message_id:string;sequence:number;sender_kind:"customer"|"responder"|"system";body:string;created_at:string};
type Session={id:string;resumeToken:string};
const storageKey="focuslab.nativeChat.session.v1";
function reconcileMessages(current:Message[],incoming:Message[]){const next=new Map(current.map((message)=>[message.client_message_id,message]));for(const message of incoming)next.set(message.client_message_id,message);return [...next.values()].sort((a,b)=>a.sequence-b.sequence||a.created_at.localeCompare(b.created_at));}
export function NativeChatPanel({apiBaseUrl=""}:{apiBaseUrl?:string}){
  const [open,setOpen]=useState(false);const [status,setStatus]=useState<"live"|"async"|"unavailable">("async");const [session,setSession]=useState<Session|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [error,setError]=useState("");const [sending,setSending]=useState(false);const socket=useRef<WebSocket|null>(null);
  useEffect(()=>{fetch(`${apiBaseUrl}/v1/chat/status`).then(async(response)=>(await response.json()) as {state?:typeof status}).then((body)=>body.state&&setStatus(body.state)).catch(()=>setStatus("async"));const saved=sessionStorage.getItem(storageKey);if(saved)try{setSession(JSON.parse(saved) as Session);}catch{sessionStorage.removeItem(storageKey);}},[apiBaseUrl]);
  useEffect(()=>{if(!session)return;let retry:number|undefined;let stopped=false;const load=()=>fetch(`${apiBaseUrl}/v1/chat/conversations/${encodeURIComponent(session.id)}/messages?resume=${encodeURIComponent(session.resumeToken)}`,{cache:"no-store"}).then(async(response)=>(await response.json()) as {messages?:Message[]}).then((body)=>setMessages((current)=>reconcileMessages(current,body.messages??[]))).catch(()=>undefined);const connect=()=>{if(stopped)return;void load();const base=new URL(apiBaseUrl||window.location.origin);base.protocol=base.protocol==="https:"?"wss:":"ws:";base.pathname=`/v1/chat/conversations/${encodeURIComponent(session.id)}/socket`;base.searchParams.set("resume",session.resumeToken);socket.current=new WebSocket(base);socket.current.onmessage=(event)=>{try{const payload=JSON.parse(String(event.data)) as {type?:string;message?:Message};if(payload.type==="message"&&payload.message)setMessages((current)=>reconcileMessages(current,[payload.message!]));}catch{/* Ignore malformed frames. */}};socket.current.onclose=()=>{if(!stopped)retry=window.setTimeout(connect,3000);};};connect();return()=>{stopped=true;if(retry)window.clearTimeout(retry);socket.current?.close();};},[apiBaseUrl,session]);
  async function start(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch(`${apiBaseUrl}/v1/chat/conversations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),phone:form.get("phone")||undefined,message:form.get("message"),website:form.get("website"),clientMessageId:crypto.randomUUID()})});const body=await response.json() as {conversation?:Session;message?:Message;error?:{message?:string}};if(!response.ok||!body.conversation||!body.message)throw new Error();setMessages([body.message]);sessionStorage.setItem(storageKey,JSON.stringify(body.conversation));setSession(body.conversation);}catch{setError("We couldn't start the conversation. Please try again. Your information is still on this page.");}finally{setSending(false);}}
  async function send(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!session)return;const form=event.currentTarget;const data=new FormData(form);const body=String(data.get("message")??"").trim();if(!body)return;const clientMessageId=crypto.randomUUID();const optimistic:Message={id:`pending:${clientMessageId}`,client_message_id:clientMessageId,sequence:messages.reduce((latest,message)=>Math.max(latest,message.sequence),0)+1,sender_kind:"customer",body,created_at:new Date().toISOString()};setMessages((current)=>reconcileMessages(current,[optimistic]));form.reset();setSending(true);setError("");try{const response=await fetch(`${apiBaseUrl}/v1/chat/conversations/${encodeURIComponent(session.id)}/messages`,{method:"POST",headers:{"Content-Type":"application/json","X-Chat-Resume-Token":session.resumeToken},body:JSON.stringify({body,clientMessageId})});const result=await response.json() as {message?:Message};if(!response.ok||!result.message)throw new Error();setMessages((current)=>reconcileMessages(current,[result.message!]));}catch{setMessages((current)=>current.filter((message)=>message.client_message_id!==clientMessageId));setError("Your message wasn't sent. Please try again.");}finally{setSending(false);}}
  return <div className="native-chat"><button type="button" aria-expanded={open} aria-controls="focuslab-chat-panel" onClick={()=>setOpen((value)=>!value)}>{status==="live"?"● Live Chat":"Send us a Message"}</button>{open?<section id="focuslab-chat-panel" role="dialog" aria-label="Focus Lab chat"><header><h2>{status==="live"?"Chat with Focus Lab":"Send Focus Lab a message"}</h2><button type="button" aria-label="Close chat" onClick={()=>setOpen(false)}>×</button></header>{session?<><ol aria-live="polite">{messages.map((message)=><li key={message.id} data-sender={message.sender_kind}><p>{message.body}</p></li>)}</ol><form onSubmit={send}><label htmlFor="native-chat-reply">Message</label><textarea id="native-chat-reply" name="message" maxLength={2000} required/><button disabled={sending}>{sending?"Sending…":"Send"}</button></form></>:<form onSubmit={start}><label>Name<input name="name" maxLength={120} required/></label><label>Email<input name="email" type="email" maxLength={254} required/></label><label>Phone (optional)<input name="phone" type="tel" maxLength={40}/></label><label>How can we help?<textarea name="message" maxLength={2000} required/></label><label className="chat-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button disabled={sending}>{sending?"Starting…":"Start conversation"}</button></form>}{error?<p role="alert">{error}</p>:null}<small>{status==="live"?"A responder is currently available.":"Leave a message for follow-up. No response time is promised."}</small></section>:null}</div>;
}
