"use client";

import { createContext,useContext,useEffect,useId,useRef,useState,type ReactNode } from "react";
import { track } from "@/lib/analytics";

type Mode="live"|"async";
type Status=Mode|"unavailable";
type Message={id:string;client_message_id:string;sequence:number;sender_kind:"customer"|"responder"|"system";body:string;created_at:string};
type Session={id:string;resumeToken:string};
type ChatContextValue={status:Status;open:boolean;openChat():void;closeChat():void};
const ChatContext=createContext<ChatContextValue|null>(null);
const storageKey="focuslab.nativeChat.session.v1";

function reconcileMessages(current:Message[],incoming:Message[]){const next=new Map(current.map((message)=>[message.client_message_id,message]));for(const message of incoming)next.set(message.client_message_id,message);return [...next.values()].sort((a,b)=>a.sequence-b.sequence||a.created_at.localeCompare(b.created_at));}

export function PublicChatProvider({children,apiBaseUrl=""}:{children:ReactNode;apiBaseUrl?:string}){
  const [status,setStatus]=useState<Status>("unavailable");const [open,setOpen]=useState(false);const [mode,setMode]=useState<Mode>("async");const [complete,setComplete]=useState(false);const [session,setSession]=useState<Session|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [error,setError]=useState("");const [sending,setSending]=useState(false);const socket=useRef<WebSocket|null>(null);const trigger=useRef<HTMLElement|null>(null);const closeButton=useRef<HTMLButtonElement>(null);const titleId=useId();
  useEffect(()=>{const controller=new AbortController();fetch(`${apiBaseUrl}/v1/chat/status`,{signal:controller.signal,cache:"no-store"}).then(async(response)=>{if(!response.ok)throw new Error();return await response.json() as {state?:Status};}).then((body)=>{if(body.state){setStatus(body.state);track(body.state==="live"?"chat_status_live":"chat_status_async");}}).catch(()=>setStatus("unavailable"));const saved=sessionStorage.getItem(storageKey);if(saved)try{setSession(JSON.parse(saved) as Session);}catch{sessionStorage.removeItem(storageKey);}return()=>controller.abort();},[apiBaseUrl]);
  useEffect(()=>{if(!open||mode!=="live"||!session)return;let retry:number|undefined;let stopped=false;const load=()=>fetch(`${apiBaseUrl}/v1/chat/conversations/${encodeURIComponent(session.id)}/messages?resume=${encodeURIComponent(session.resumeToken)}`,{cache:"no-store"}).then(async(response)=>(await response.json()) as {messages?:Message[]}).then((body)=>setMessages((current)=>reconcileMessages(current,body.messages??[]))).catch(()=>undefined);const connect=()=>{if(stopped)return;void load();const base=new URL(apiBaseUrl||window.location.origin);base.protocol=base.protocol==="https:"?"wss:":"ws:";base.pathname=`/v1/chat/conversations/${encodeURIComponent(session.id)}/socket`;base.searchParams.set("resume",session.resumeToken);socket.current=new WebSocket(base);socket.current.onmessage=(event)=>{try{const payload=JSON.parse(String(event.data)) as {type?:string;message?:Message};if(payload.type==="message"&&payload.message)setMessages((current)=>reconcileMessages(current,[payload.message!]));}catch{/* Ignore malformed frames. */}};socket.current.onclose=()=>{if(!stopped)retry=window.setTimeout(connect,3000);};};connect();return()=>{stopped=true;if(retry)window.clearTimeout(retry);socket.current?.close();};},[apiBaseUrl,mode,open,session]);
  useEffect(()=>{if(!open)return;const previousOverflow=document.body.style.overflow;document.body.style.overflow="hidden";closeButton.current?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==="Escape")closeChat();if(event.key==="Tab"){const panel=document.getElementById("focuslab-chat-panel");const controls=panel?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea:not([disabled])');if(!controls?.length)return;const first=controls[0]!,last=controls[controls.length-1]!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener("keydown",keydown);return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener("keydown",keydown);};},[open]);
  function openChat(){if(status==="unavailable")return;trigger.current=document.activeElement as HTMLElement;setMode(status);setComplete(false);setError("");setOpen(true);track("chat_action_clicked",{state:status});}
  function closeChat(){setOpen(false);window.setTimeout(()=>{const opener=trigger.current?.isConnected?trigger.current:document.querySelector<HTMLElement>('[aria-controls="mobile-menu"]');opener?.focus();},0);}
  async function start(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setError("");const formElement=event.currentTarget;const form=new FormData(formElement);try{const response=await fetch(`${apiBaseUrl}/v1/chat/conversations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),phone:form.get("phone")||undefined,message:form.get("message"),website:form.get("website"),clientMessageId:crypto.randomUUID()})});const body=await response.json() as {conversation?:Session;message?:Message};if(!response.ok||!body.conversation||!body.message)throw new Error();sessionStorage.setItem(storageKey,JSON.stringify(body.conversation));setSession(body.conversation);setMessages([body.message]);if(mode==="async")setComplete(true);formElement.reset();}catch{setError("We couldn't send your message. Please try again. Your information is still on this page.");}finally{setSending(false);}}
  async function send(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!session)return;const form=event.currentTarget;const body=String(new FormData(form).get("message")??"").trim();if(!body)return;const clientMessageId=crypto.randomUUID();const optimistic:Message={id:`pending:${clientMessageId}`,client_message_id:clientMessageId,sequence:messages.reduce((latest,message)=>Math.max(latest,message.sequence),0)+1,sender_kind:"customer",body,created_at:new Date().toISOString()};setMessages((current)=>reconcileMessages(current,[optimistic]));form.reset();setSending(true);setError("");try{const response=await fetch(`${apiBaseUrl}/v1/chat/conversations/${encodeURIComponent(session.id)}/messages`,{method:"POST",headers:{"Content-Type":"application/json","X-Chat-Resume-Token":session.resumeToken},body:JSON.stringify({body,clientMessageId})});const result=await response.json() as {message?:Message};if(!response.ok||!result.message)throw new Error();setMessages((current)=>reconcileMessages(current,[result.message!]));}catch{setMessages((current)=>current.filter((message)=>message.client_message_id!==clientMessageId));setError("Your message wasn't sent. Please try again.");}finally{setSending(false);}}
  return <ChatContext.Provider value={{status,open,openChat,closeChat}}>{children}{open?<div className="public-chat-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)closeChat();}}><section id="focuslab-chat-panel" className="public-chat-drawer" role="dialog" aria-modal="true" aria-labelledby={titleId}><header><div><p>{mode==="live"?"Responder available":"Contact Focus Lab"}</p><h2 id={titleId}>{mode==="live"?"Chat with Focus Lab":"Send us a Message"}</h2></div><button ref={closeButton} type="button" aria-label="Close chat" onClick={closeChat}>×</button></header>{mode==="async"&&complete?<div className="public-chat-complete" role="status"><h3>Thanks — your message has been sent.</h3><p>We’ll get back to you. You’re free to close this window or leave the website.</p><button type="button" onClick={closeChat}>Done</button></div>:mode==="live"&&session?<><ol className="public-chat-messages" aria-live="polite">{messages.map((message)=><li key={message.id} data-sender={message.sender_kind}><p>{message.body}</p></li>)}</ol><form onSubmit={send}><label htmlFor="native-chat-reply">Message</label><textarea id="native-chat-reply" name="message" maxLength={2000} autoComplete="off" required/><button disabled={sending}>{sending?"Sending…":"Send"}</button></form></>:<form onSubmit={start}><label>Name<input name="name" autoComplete="name" maxLength={120} required/></label><label>Email<input name="email" type="email" inputMode="email" autoComplete="email" spellCheck={false} maxLength={254} required/></label><label>Phone (optional)<input name="phone" type="tel" inputMode="tel" autoComplete="tel" maxLength={40}/></label><label>How can we help?<textarea name="message" autoComplete="off" maxLength={2000} required/></label><label className="chat-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button disabled={sending}>{sending?"Sending…":mode==="live"?"Start Conversation":"Send Message"}</button></form>}{error?<p className="public-chat-error" role="alert">{error}</p>:null}<small>{mode==="live"?"A responder is currently available. No response-time guarantee is implied.":"Send your message and continue with your day. No response time is promised."}</small></section></div>:null}</ChatContext.Provider>;
}

export function PublicChatTrigger({className="",onOpen}:{className?:string;onOpen?:()=>void}){const chat=useContext(ChatContext);if(!chat||chat.status==="unavailable")return null;return <button type="button" className={className} aria-haspopup="dialog" aria-expanded={chat.open} onClick={()=>{onOpen?.();chat.openChat();}}>{chat.status==="live"?<span aria-hidden="true">● </span>:null}{chat.status==="live"?"Live Chat (No Bots)":"Message Us (No Bots)"}</button>;}

/** Standalone development surface; the public site uses PublicChatProvider and PublicChatTrigger. */
export function NativeChatPanel({apiBaseUrl=""}:{apiBaseUrl?:string}){return <div className="native-chat"><PublicChatProvider apiBaseUrl={apiBaseUrl}><PublicChatTrigger/></PublicChatProvider></div>;}
