import { useCallback,useEffect,useRef,useState } from "react";
import type { OperationsClient } from "../lib/api";
import type { Conversation,ConversationDetail,OperationsStatus } from "../lib/types";
import { Empty,ErrorState,Loading } from "../components/AsyncState";
import { formatDateTime,humanize } from "../lib/format";
import { chatAudio,createAlertDeduplicator,notifyChatEvent,setSoundsEnabled,soundsEnabled,type ChatAlertEvent,type ChatAudioState } from "../lib/chatNotifications";

export function ChatView({client,status,currentResponderId,audioState,onAudioStateChange}:{client:OperationsClient;status:OperationsStatus|null;currentResponderId:string;audioState:ChatAudioState;onAudioStateChange:(state:ChatAudioState)=>void}){
  const [items,setItems]=useState<Conversation[]>([]);const [audioTestStatus,setAudioTestStatus]=useState("");const [selected,setSelected]=useState<ConversationDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [reply,setReply]=useState("");const [saving,setSaving]=useState(false);const [socketState,setSocketState]=useState("Connecting");const [sounds,setSounds]=useState(()=>soundsEnabled());const acceptEvent=useRef(createAlertDeduplicator());
  const load=useCallback(async()=>{const result=await client.conversations();setItems(result.conversations);setError("");setLoading(false);},[client]);
  const open=useCallback(async(id:string)=>{try{setSelected(await client.conversation(id));await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not open conversation.");}},[client,load]);
  useEffect(()=>{void load().catch((reason)=>{setError(reason instanceof Error?reason.message:"Could not load conversations.");setLoading(false);});},[load]);
  useEffect(()=>{let socket:WebSocket|undefined;let retry:number|undefined;let stopped=false;const connect=()=>{if(stopped)return;try{socket=client.chatEventsSocket();socket.onopen=()=>setSocketState("Connected");socket.onmessage=(event)=>{if(event.data==="pong")return;try{const payload=JSON.parse(String(event.data)) as Partial<ChatAlertEvent>;if(!payload.id||!payload.type||!payload.conversationId)return;void notifyChatEvent(payload as ChatAlertEvent,{sounds,activeConversationId:selected?.conversation.id,acceptEvent:acceptEvent.current}).then(()=>onAudioStateChange(chatAudio.state()));void load();if(selected?.conversation.id===payload.conversationId)void open(payload.conversationId!);}catch{/* Ignore malformed event frames. */}};socket.onclose=()=>{setSocketState("Reconnecting");if(!stopped)retry=window.setTimeout(connect,3000);};socket.onerror=()=>setSocketState("Connection lost");}catch{setSocketState("Connection lost");}};connect();return()=>{stopped=true;if(retry)window.clearTimeout(retry);socket?.close();};},[client,load,onAudioStateChange,open,selected?.conversation.id,sounds]);
  async function send(event:React.FormEvent){event.preventDefault();const body=reply.trim();if(!body||!selected||saving)return;setSaving(true);try{await client.reply(selected.conversation.id,body);setReply("");await open(selected.conversation.id);}catch(reason){setError(reason instanceof Error?reason.message:"Reply was not sent.");}finally{setSaving(false);}}
  async function assignSelf(){if(!selected)return;try{await client.conversationAssignment(selected.conversation.id,currentResponderId);await open(selected.conversation.id);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Assignment was not saved.");}}
  async function toggleSounds(){if(sounds&&audioState!=="running"){await chatAudio.unlock();await chatAudio.play("message:new");onAudioStateChange(chatAudio.state());return;}const next=!sounds;setSounds(next);setSoundsEnabled(next);if(next){await chatAudio.unlock();await chatAudio.play("message:new");onAudioStateChange(chatAudio.state());}}
  async function testSound(){const state=await chatAudio.unlock();const played=await chatAudio.play("conversation:new");onAudioStateChange(chatAudio.state());setAudioTestStatus(played?"Test sound started. If it is inaudible, check the desktop tab, site, system output, and volume mixer.":`Audio did not start (${state}). Interact with the page and try again.`);}
  const showAudioDiagnostics=import.meta.env.VITE_APP_STAGE==="staging";const soundLabel=!sounds?"Sounds Off":audioState==="running"?"Sounds On · Ready":"Sounds On · Tap to enable";return <section className="view"><div className="view-heading"><div><p className="eyebrow">Native Focus Lab Channel</p><h1>Chat</h1><p>Website conversations are stored in D1 and delivered live through Cloudflare WebSockets.</p></div><div className="sound-controls"><button className="button secondary" onClick={()=>void toggleSounds()}>{soundLabel}</button>{showAudioDiagnostics?<button className="button secondary" onClick={()=>void testSound()}>Test Notification Sound</button>:null}<small className="muted" aria-live="polite">Audio: {audioState}. Event stream: {socketState}.{audioTestStatus?` ${audioTestStatus}`:""}</small></div></div>
    <div className="status-grid"><article className="metric-card"><span>Customer-facing state</span><strong>{status?.chat.label??"Checking…"}</strong><small>{status?.activeResponders.length??0} confirmed live responder(s)</small></article><article className="metric-card"><span>Native inbox</span><strong>{items.reduce((sum,item)=>sum+Number(item.unread_count||0),0)} unread</strong><small>External channels remain future adapters</small></article></div>
    {error?<ErrorState message={error}/>:null}<div className={`chat-workspace ${selected?"conversation-open":""}`}><div className="conversation-index"><h2 className="section-title">Conversations</h2>{loading?<Loading label="Loading conversations…"/>:!items.length?<Empty title="No website conversations" detail="New native chats will appear here."/>:<div className="conversation-list">{items.map((item)=><button className={`conversation-card ${selected?.conversation.id===item.id?"selected":""}`} onClick={()=>void open(item.id)} key={item.id}><div><h3>{item.full_name}</h3><p>{item.provider==="native_web"?"Website chat":humanize(item.provider)}</p></div><div>{Number(item.unread_count)>0?<span className="badge warning">{item.unread_count} unread</span>:<span className="badge neutral">Read</span>}<time dateTime={item.last_message_at??item.updated_at}>{formatDateTime(item.last_message_at??item.updated_at)}</time></div></button>)}</div>}</div>
      <div className="chat-detail">{!selected?<Empty title="Choose a conversation" detail="Customer messages and reply controls will appear here."/>:<><button type="button" className="button text chat-back" onClick={()=>setSelected(null)}>← Conversations</button><header><div><p className="eyebrow">Customer</p><h2>{selected.conversation.full_name}</h2><p>{selected.conversation.email}{selected.conversation.phone?` · ${selected.conversation.phone}`:""}</p></div><div>{selected.conversation.assigned_responder_id?<span className="badge neutral">Assigned: {selected.conversation.assigned_responder_label}</span>:<button className="button secondary" onClick={()=>void assignSelf()}>Assign myself</button>}</div></header><ol className="message-list" aria-label="Conversation messages">{selected.messages.map((message)=><li className={message.sender_kind==="customer"?"customer-message":"staff-message"} key={message.id}><strong>{message.sender_kind==="customer"?selected.conversation.full_name:message.sender_label??"Focus Lab staff"}</strong><p>{message.body}</p><time dateTime={message.created_at}>{formatDateTime(message.created_at)}</time></li>)}</ol><form onSubmit={send} className="reply-form"><label htmlFor="chat-reply">Reply</label><textarea id="chat-reply" maxLength={2000} value={reply} onChange={(event)=>setReply(event.target.value)} required/><button className="button primary" disabled={saving||!reply.trim()}>{saving?"Sending…":"Send reply"}</button></form></>}</div></div>
  </section>;
}
