import { useEffect,useMemo,useState } from "react";
import type { OperationsClient } from "../lib/api";
import type { InboxResponse,Responder,WorkflowState } from "../lib/types";
import { workflowStates } from "../lib/types";
import { useDebounced } from "../lib/hooks";
import { formatDateRange,formatDateTime,splitPipe } from "../lib/format";
import { buildInboxParams } from "../lib/inbox-query";
import { CapacityBadge,WorkflowBadge } from "../components/Badges";
import { Empty,ErrorState,Loading } from "../components/AsyncState";

export function InboxView({ client,responders,currentResponderId,initialQuery="",title="Inquiry Inbox" }:{ client:OperationsClient;responders:Responder[];currentResponderId:string;initialQuery?:string;title?:string }){
  const [query,setQuery]=useState(initialQuery);const debounced=useDebounced(query);const [workflow,setWorkflow]=useState<WorkflowState|"active"|"all">("active");const [assignment,setAssignment]=useState("all");
  const [data,setData]=useState<InboxResponse>();const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [offset,setOffset]=useState(0);
  const params=useMemo(()=>buildInboxParams({query:debounced,workflow,assignment,currentResponderId,offset}),[assignment,currentResponderId,debounced,offset,workflow]);
  useEffect(()=>{let active=true;setLoading(true);setError("");client.inbox(params).then((result)=>{if(active){const filtered=workflow==="active"?result.inquiries.filter((item)=>!["won","lost","archived"].includes(item.workflow_state)):result.inquiries;setData({ ...result,inquiries:filtered });}}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"Could not load inquiries.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[client,params,workflow]);
  return <section className="view"><div className="view-heading"><div><p className="eyebrow">CRM</p><h1>{title}</h1><p>New and active opportunities requiring human review.</p></div>{data?<span className="count-pill">{data.page.total} records</span>:null}</div>
    <div className="filters"><label className="search-field">Search inquiries<input type="search" name="inquirySearch" autoComplete="off" placeholder="Name, venue, date, event…" value={query} onChange={(event)=>{setQuery(event.target.value);setOffset(0);}}/></label><label>Workflow<select value={workflow} onChange={(event)=>{setWorkflow(event.target.value as typeof workflow);setOffset(0);}}><option value="active">Active</option><option value="all">All</option>{workflowStates.map((state)=><option key={state} value={state}>{state.replaceAll("_"," ")}</option>)}</select></label><label>Assignment<select value={assignment} onChange={(event)=>{setAssignment(event.target.value);setOffset(0);}}><option value="all">Everyone</option><option value="mine">Assigned to me</option><option value="unassigned">Unassigned</option>{responders.map((responder)=><option key={responder.id} value={responder.id}>{responder.display_label}</option>)}</select></label></div>
    {loading?<Loading label="Loading inquiry inbox…"/>:error?<ErrorState message={error}/>:!data?.inquiries.length?<Empty title="No matching inquiries" detail="Change the filters or wait for a new inquiry."/>:<div className="inbox-list">{data.inquiries.map((item)=>{const services=splitPipe(item.services);const assignees=splitPipe(item.assignee_labels);return <a className="inbox-card" href={`#/inquiry/${encodeURIComponent(item.id)}`} key={item.id}><div className="card-primary"><div className="card-title-row"><h2>{item.full_name}</h2><WorkflowBadge state={item.workflow_state}/></div><p className="event-line"><strong>{item.event_family??"Event type pending"}</strong> · {formatDateRange(item.start_date,item.end_date)}</p><p className="muted truncate">{item.venue_location??"Venue not supplied"}</p><div className="badge-row"><CapacityBadge blocks={item.blocks_capacity===1}/>{services.slice(0,3).map((service)=><span className="badge neutral" key={service}>{service}</span>)}{services.length>3?<span className="badge neutral">+{services.length-3}</span>:null}</div></div><div className="card-meta"><span>{assignees.length?assignees.join(", "):"Unassigned"}</span><time dateTime={item.created_at}>Created {formatDateTime(item.created_at)}</time></div></a>;})}</div>}
    {data?<div className="pagination"><button className="button secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><span>{offset+1}–{Math.min(offset+25,data.page.total)} of {data.page.total}</span><button className="button secondary" disabled={!data.page.hasMore} onClick={()=>setOffset(offset+25)}>Next</button></div>:null}
  </section>;
}
