import { useCallback,useEffect,useState,type FormEvent } from "react";
import type { OperationsClient } from "../lib/api";
import type { Assessment,InquiryDetail,Responder,WorkflowState } from "../lib/types";
import { workflowStates } from "../lib/types";
import { CapacityBadge,ConflictBadge,WorkflowBadge } from "../components/Badges";
import { ErrorState,Loading } from "../components/AsyncState";
import { formatDateRange,formatDateTime,humanize,numberValue,text } from "../lib/format";
import { businessProfile } from "../lib/business-profile";

export function InquiryDetailView({ client,id,responders,currentResponderId,online }:{ client:OperationsClient;id:string;responders:Responder[];currentResponderId:string;online:boolean }){
  const [detail,setDetail]=useState<InquiryDetail>();const [assessment,setAssessment]=useState<Assessment>();const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [saving,setSaving]=useState("");const [notice,setNotice]=useState("");const [note,setNote]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const nextDetail=await client.detail(id);setDetail(nextDetail);if(businessProfile.capabilities.event&&nextDetail.inquiry.event_id){const nextAssessment=await client.conflicts(id);setAssessment(nextAssessment.assessment);}else setAssessment(undefined);}catch(reason){setError(reason instanceof Error?reason.message:"Could not load inquiry details.");}finally{setLoading(false);}},[client,id]);
  useEffect(()=>{void load();},[load]);
  async function mutate(label:string,operation:()=>Promise<unknown>){if(!online){setNotice("You’re offline. Reconnect before saving changes.");return false;}setSaving(label);setNotice("");try{await operation();setNotice("Saved successfully.");await load();return true;}catch(reason){setNotice(reason instanceof Error?`Not saved: ${reason.message}`:"Not saved. Try again.");return false;}finally{setSaving("");}}
  async function addNote(event:FormEvent){event.preventDefault();const body=note.trim();if(!body){setNotice("Enter an internal note before saving.");return;}if(await mutate("note",()=>client.note(id,body)))setNote("");}
  if(loading)return <Loading label="Loading inquiry detail…"/>;if(error)return <ErrorState message={error} onRetry={()=>void load()}/>;if(!detail)return <ErrorState message="Inquiry not found."/>;
  const row=detail.inquiry;const workflow=(text(row.workflow_state)??"new") as WorkflowState;const blocks=numberValue(row.blocks_capacity)===1;const assignments=new Set(detail.assignments.map((item)=>item.responder_id));
  return <article className="view detail-view"><div className="detail-heading"><div><a href="#/inbox" className="back-link">← Back to Inbox</a><p className="eyebrow">Inquiry Detail</p><h1>{text(row.full_name)??"Customer name unavailable"}</h1><div className="badge-row"><WorkflowBadge state={workflow}/>{businessProfile.capabilities.capacity&&row.event_id?<CapacityBadge blocks={blocks}/>:null}{assessment?<ConflictBadge state={assessment.status}/>:null}</div></div><div className="detail-actions"><button className="button secondary" disabled={Boolean(saving)||!online} onClick={()=>void mutate("assign-self",()=>client.assignment(id,currentResponderId,!assignments.has(currentResponderId)))}>{assignments.has(currentResponderId)?"Unassign Myself":"Assign to Me"}</button></div></div>
    {notice?<div className={`save-notice ${notice.startsWith("Saved")?"success":""}`} role="status" aria-live="polite">{notice}</div>:null}
    <div className="detail-grid"><section className="panel"><h2>Customer</h2><dl><dt>Email</dt><dd>{text(row.email)?<a href={`mailto:${text(row.email)}`}>{text(row.email)}</a>:"Not supplied"}</dd><dt>Phone</dt><dd>{text(row.phone)?<a href={`tel:${text(row.phone)}`}>{text(row.phone)}</a>:"Not supplied"}</dd><dt>Preferred contact</dt><dd>{humanize(text(row.preferred_contact)??"not supplied")}</dd></dl>{text(row.customer_note)?<div className="customer-note"><strong>Customer details</strong><p className="break-words">{text(row.customer_note)}</p></div>:null}</section>
    {businessProfile.capabilities.event&&detail.event?<section className="panel"><h2>Event</h2><dl><dt>Event family</dt><dd>{text(row.event_family)??"Not supplied"}</dd><dt>Date</dt><dd>{formatDateRange(text(row.start_date),text(row.end_date))}</dd><dt>Time</dt><dd>{text(row.start_time)&&text(row.end_time)?`${text(row.start_time)}–${text(row.end_time)}`:"Time not supplied"}</dd><dt>Venue/location</dt><dd className="break-words">{text(row.venue_location)??"Not supplied"}</dd><dt>Guest count</dt><dd>{numberValue(row.guest_count)??"Not supplied"}</dd><dt>Requested services</dt><dd>{detail.services.length?detail.services.map((item)=>item.service_name).join(", "):"None supplied"}</dd></dl></section>:null}
    {detail.consulting?<section className="panel"><h2>Consulting</h2><dl><dt>Organization</dt><dd>{detail.consulting.organization??"Not supplied"}</dd><dt>Offer/service area</dt><dd>{detail.consulting.offer_service_area??"Not supplied"}</dd><dt>Situation/problem</dt><dd className="break-words">{detail.consulting.situation_problem??"Not supplied"}</dd><dt>Desired outcome</dt><dd className="break-words">{detail.consulting.desired_outcome??"Not supplied"}</dd><dt>Timeline</dt><dd>{detail.consulting.timeline??"Not supplied"}</dd><dt>Budget</dt><dd>{detail.consulting.budget??"Not supplied"}</dd><dt>Country/region</dt><dd>{detail.consulting.country_region??"Not supplied"}</dd><dt>Referral/source</dt><dd>{detail.consulting.referral_source??"Not supplied"}</dd></dl></section>:null}
    <section className="panel"><h2>Workflow</h2><label>Internal workflow state<select value={workflow} disabled={Boolean(saving)||!online} onChange={(event)=>void mutate("workflow",()=>client.workflow(id,event.target.value as WorkflowState))}>{workflowStates.map((state)=><option key={state} value={state}>{humanize(state)}</option>)}</select></label><div className="assignment-list"><h3>Assignments</h3>{responders.map((responder)=><label className="check-row" key={responder.id}><input type="checkbox" checked={assignments.has(responder.id)} disabled={Boolean(saving)||!online} onChange={(event)=>void mutate("assignment",()=>client.assignment(id,responder.id,event.target.checked))}/><span>{responder.display_label}</span></label>)}</div>{businessProfile.capabilities.capacity&&row.event_id?<><button className={`button ${blocks?"secondary":"warning"}`} disabled={Boolean(saving)||!online} onClick={()=>void mutate("capacity",()=>client.capacity(id,!blocks))}>{blocks?"Stop Blocking Capacity":"Mark as Capacity-Blocking"}</button><p className="help-text">This internal control does not notify the customer or confirm a booking.</p></>:null}<dl><dt>Created</dt><dd>{formatDateTime(text(row.created_at))}</dd><dt>Updated</dt><dd>{formatDateTime(text(row.updated_at))}</dd></dl></section>
    {businessProfile.capabilities.schedule&&detail.event?<section className="panel"><h2>Scheduling Review</h2>{assessment?<><ConflictBadge state={assessment.status}/><p className="panel-lede">{scheduleExplanation(assessment)}</p><dl><dt>Configured capacity</dt><dd>{assessment.capacity}</dd><dt>Definite blocking overlaps</dt><dd>{assessment.blockingOverlapCount}</dd><dt>Related records</dt><dd>{assessment.conflicts.length||"None"}</dd></dl></>:<p>Scheduling assessment unavailable.</p>}</section>:null}
    <section className="panel span-two"><h2>Internal Notes</h2><p className="internal-label">Internal only · never customer-visible</p><form onSubmit={addNote} className="note-form"><label htmlFor="internal-note">Add internal note</label><textarea id="internal-note" name="internalNote" maxLength={4000} rows={4} value={note} onChange={(event)=>setNote(event.target.value)} placeholder="Record follow-up context…" disabled={!online}/><div><span className="character-count">{note.length}/4000</span><button className="button primary" disabled={saving==="note"||!online}>{saving==="note"?"Saving…":"Save Internal Note"}</button></div></form><div className="timeline">{detail.notes.length?detail.notes.map((item)=><article key={item.id}><header><strong>{item.author_label??"Unknown responder"}</strong><time dateTime={item.created_at}>{formatDateTime(item.created_at)}</time></header><p className="break-words">{item.body}</p></article>):<p className="muted">No internal notes yet.</p>}</div></section>
    <section className="panel"><h2>Activity</h2><div className="timeline compact">{detail.activities.map((item)=><article key={item.id}><header><strong>{humanize(item.activity_type)}</strong><time dateTime={item.created_at}>{formatDateTime(item.created_at)}</time></header><p>{item.actor_id?`Responder: ${responderLabel(item.actor_id,responders)}`:humanize(item.actor_kind)}</p></article>)}</div></section>
    <section className="panel"><h2>Conversation</h2>{detail.conversations.length?detail.conversations.map((conversation)=><dl key={conversation.id}><dt>Provider</dt><dd>{conversation.provider}</dd><dt>Channel state</dt><dd>{humanize(conversation.channel_state)}</dd><dt>External thread</dt><dd className="break-words">{conversation.external_conversation_id??"Not connected"}</dd></dl>):<p className="muted">No provider conversation metadata exists for this inquiry.</p>}</section></div>
  </article>;
}
function scheduleExplanation(value:Assessment){if(value.status==="clear")return "No capacity-blocking overlap is currently recorded. This is internal guidance, not a customer availability promise.";if(value.status==="potential_conflict")return "A date overlaps, but incomplete timing prevents a definitive result. Review manually.";if(value.status==="capacity_conflict")return "The configured capacity is reached by definite overlapping capacity-blocking records.";return "The event does not contain enough scheduling information for a definitive assessment.";}
function responderLabel(id:string,responders:Responder[]){return responders.find((item)=>item.id===id)?.display_label??id;}
