import { useEffect,useState } from "react";
import type { OperationsClient } from "../lib/api";
import type { ScheduleEvent } from "../lib/types";
import { CapacityBadge,ConflictBadge,WorkflowBadge } from "../components/Badges";
import { Empty,ErrorState,Loading } from "../components/AsyncState";
import { formatDateRange,splitPipe } from "../lib/format";
import { monthRange } from "../lib/schedule";

export function ScheduleView({ client }:{ client:OperationsClient }){
  const [anchor,setAnchor]=useState(()=>new Date());const range=monthRange(anchor);const [events,setEvents]=useState<ScheduleEvent[]>([]);const [state,setState]=useState("all");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{let active=true;setLoading(true);setError("");client.schedule(range.start,range.end,state).then((result)=>{if(active)setEvents(result.events);}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"Could not load the schedule.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[anchor,client,range.end,range.start,state]);
  const move=(delta:number)=>setAnchor(new Date(anchor.getFullYear(),anchor.getMonth()+delta,1));
  return <section className="view"><div className="view-heading"><div><p className="eyebrow">Decision Support</p><h1>Schedule</h1><p>Opportunities do not reserve capacity unless staff explicitly marks them blocking.</p></div></div><div className="schedule-toolbar"><button className="button secondary" onClick={()=>move(-1)} aria-label="Previous month">←</button><h2>{range.label}</h2><button className="button secondary" onClick={()=>move(1)} aria-label="Next month">→</button><label>Event state<select value={state} onChange={(event)=>setState(event.target.value)}><option value="all">All states</option><option value="requested">Requested</option><option value="tentative">Tentative</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option><option value="declined">Declined</option></select></label></div>
    {loading?<Loading label="Loading schedule…"/>:error?<ErrorState message={error}/>:!events.length?<Empty title="No events in this range" detail="Navigate to another month or change the event-state filter."/>:<div className="schedule-list">{events.map((event)=><a className="schedule-card" href={`#/inquiry/${encodeURIComponent(event.inquiry_id)}`} key={event.id}><time dateTime={event.start_date} className="date-block"><strong>{new Intl.DateTimeFormat(undefined,{day:"numeric"}).format(new Date(`${event.start_date}T12:00:00`))}</strong><span>{new Intl.DateTimeFormat(undefined,{month:"short"}).format(new Date(`${event.start_date}T12:00:00`))}</span></time><div className="min-width-zero"><div className="card-title-row"><h2>{event.event_family??"Event type pending"}</h2><ConflictBadge state={event.assessment.status}/></div><p>{event.full_name} · {formatDateRange(event.start_date,event.end_date)}</p><p className="muted truncate">{event.venue_location??"Venue not supplied"}</p><div className="badge-row"><CapacityBadge blocks={event.blocks_capacity===1}/><WorkflowBadge state={event.workflow_state}/>{splitPipe(event.services).slice(0,2).map((service)=><span className="badge neutral" key={service}>{service}</span>)}</div>{event.assessment.requiresHumanReview?<p className="review-reason">Human review required: {event.assessment.conflicts.length?`${event.assessment.conflicts.length} overlapping capacity record(s).`:"timing information is incomplete."}</p>:null}</div></a>)}</div>}
  </section>;
}
